// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/pgvector/pgvector-go"
)

type Quote struct {
	ID        int64
	Content   string
	Author    string
	Embedding pgvector.Vector
}
