services:
  api:
    container_name: api
    build:
      context: .
      target: dev
    command: ["air"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: ankane/pgvector
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      

volumes:
  pgdata: